services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: moneywise-app
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        environment:
            DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${DB_NAME}
        depends_on:
            - db_container
        networks:
            - moneywise-network
        command: >
            sh -c "./wait-for-it.sh ${DOCKER_DB_HOST}:${DOCKER_DB_PORT} -- flask db upgrade && python app.py"
        volumes:
            - .:/app

    db_container:
        image: postgres:13
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PUBLIC_PORT}:${DOCKER_DB_PORT}"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - moneywise-network

volumes:
    db-data:

networks:
    moneywise-network:
        driver: bridge
